export const elements = [
  {
    id: 'pieza-001',
    nfcSerial: '04:A1:B2:C3:D4:E5:80',
    number: '01',
    category: 'Colección permanente',
    title: 'Materia y memoria',
    author: 'Elena Soler',
    year: '2024',
    description: 'Una exploración táctil sobre el paso del tiempo, construida con materiales recuperados y pigmentos naturales.',
    detail: 'La pieza cambia sutilmente con la luz. Acércate a los bordes para descubrir las capas que revelan su proceso de creación.',
    color: '#d9ff43',
  },
  {
    id: 'pieza-002',
    nfcSerial: '04:B2:C3:D4:E5:F6:91',
    number: '02',
    category: 'Archivo sonoro',
    title: 'Ecos del agua',
    author: 'Martín Cobo',
    year: '2023',
    description: 'Paisajes sonoros recogidos a lo largo del Mediterráneo y convertidos en una cartografía emocional.',
    detail: 'Cada fragmento corresponde a una coordenada distinta. La composición completa dura once minutos.',
    color: '#a8d8ea',
  },
  {
    id: 'pieza-003',
    nfcSerial: '04:C3:D4:E5:F6:A7:02',
    number: '03',
    category: 'Instalación',
    title: 'Umbral',
    author: 'Noa Vidal',
    year: '2025',
    description: 'Una estructura que reacciona a la presencia y convierte el movimiento del público en luz.',
    detail: 'Los sensores interpretan la distancia, no registran imágenes ni almacenan información personal.',
    color: '#ff9e80',
  },
  // Fichas de ejemplo: sustituir los datos y los números NFC por los reales.
  {
    id: 'pieza-004',
    nfcSerial: '04:D4:E5:F6:A7:B8:04',
    number: '04',
    category: 'Escultura',
    title: 'Equilibrio cotidiano',
    author: 'Lucía Ferrer',
    year: '2024',
    description: 'Una composición de formas apiladas que explora el equilibrio entre el peso y la fragilidad.',
    detail: 'Los elementos se sostienen por su propia distribución. Observa cómo cambia la silueta desde cada lado.',
    color: '#e8c4a2',
  },
  {
    id: 'pieza-005',
    nfcSerial: '04:D4:E5:F6:A7:B8:05',
    number: '05',
    category: 'Fotografía',
    title: 'La hora azul',
    author: 'Pablo Ríos',
    year: '2023',
    description: 'Una serie fotográfica sobre los instantes en que la ciudad pierde sus colores y empieza a iluminarse.',
    detail: 'Las imágenes se tomaron al anochecer. Los reflejos conectan espacios que parecen separados.',
    color: '#b6c9ef',
  },
  {
    id: 'pieza-006',
    nfcSerial: '04:D4:E5:F6:A7:B8:06',
    number: '06',
    category: 'Textil',
    title: 'Hilos de casa',
    author: 'Sara Beltrán',
    year: '2025',
    description: 'Un tejido de retales domésticos que reúne recuerdos a través del color, las costuras y las texturas.',
    detail: 'Cada unión conserva visible su puntada. Los fragmentos mantienen las marcas de su uso anterior.',
    color: '#f2b8c6',
  },
  {
    id: 'pieza-007',
    nfcSerial: '04:D4:E5:F6:A7:B8:07',
    number: '07',
    category: 'Cerámica',
    title: 'Tierra adentro',
    author: 'Diego Marín',
    year: '2024',
    description: 'Una familia de recipientes modelados a mano que recoge las irregularidades del paisaje.',
    detail: 'La superficie combina zonas esmaltadas con barro al descubierto. Las huellas del modelado forman parte de la obra.',
    color: '#d7ad8c',
  },
  {
    id: 'pieza-008',
    nfcSerial: '04:D4:E5:F6:A7:B8:08',
    number: '08',
    category: 'Instalación',
    title: 'Jardín suspendido',
    author: 'Aina Costa',
    year: '2025',
    description: 'Formas vegetales suspendidas dibujan un jardín que se transforma con las corrientes de aire.',
    detail: 'Las sombras proyectadas completan la composición y varían según la posición de la luz.',
    color: '#b9d9ad',
  },
  {
    id: 'pieza-009',
    nfcSerial: '04:D4:E5:F6:A7:B8:09',
    number: '09',
    category: 'Obra gráfica',
    title: 'Mapa de ausencias',
    author: 'Hugo Serra',
    year: '2022',
    description: 'Un grabado que representa una ciudad imaginada a través de sus vacíos, recorridos y límites.',
    detail: 'Las líneas superpuestas proceden de varias pasadas de impresión. Los espacios sin tinta actúan como lugares de encuentro.',
    color: '#ddd3b6',
  },
  {
    id: 'pieza-010',
    nfcSerial: '04:D4:E5:F6:A7:B8:10',
    number: '10',
    category: 'Archivo sonoro',
    title: 'Voces del patio',
    author: 'Clara Montes',
    year: '2024',
    description: 'Una composición de sonidos cotidianos que reconstruye la vida compartida de un patio interior.',
    detail: 'Pasos, conversaciones y ventanas componen distintas capas de escucha a lo largo de la grabación.',
    color: '#a8d8ce',
  },
  {
    id: 'pieza-011',
    nfcSerial: '04:D4:E5:F6:A7:B8:11',
    number: '11',
    category: 'Pintura',
    title: 'Después de la lluvia',
    author: 'Bruno Leal',
    year: '2023',
    description: 'Un paisaje abstracto construido con veladuras que evocan la humedad y los reflejos sobre el suelo.',
    detail: 'Las capas transparentes permiten descubrir tonos anteriores bajo la superficie de la pintura.',
    color: '#b4c8d1',
  },
  {
    id: 'pieza-012',
    nfcSerial: '04:D4:E5:F6:A7:B8:12',
    number: '12',
    category: 'Escultura',
    title: 'Pliegue',
    author: 'Inés Pardo',
    year: '2025',
    description: 'Una lámina de metal doblada convierte un gesto sencillo en una estructura de luces y sombras.',
    detail: 'Los bordes y las caras reflejan el entorno de forma distinta. La obra propone recorrer su perímetro.',
    color: '#c9c4df',
  },
  {
    id: 'pieza-013',
    nfcSerial: '04:D4:E5:F6:A7:B8:13',
    number: '13',
    category: 'Fotografía',
    title: 'Distancia mínima',
    author: 'Leo Navarro',
    year: '2024',
    description: 'Detalles de objetos comunes fotografiados de cerca revelan paisajes que suelen pasar desapercibidos.',
    detail: 'La escala de la imagen invita a reconocer el objeto a partir de su textura y sus pequeñas imperfecciones.',
    color: '#efcf9f',
  },
  {
    id: 'pieza-014',
    nfcSerial: '04:D4:E5:F6:A7:B8:14',
    number: '14',
    category: 'Libro de artista',
    title: 'Páginas del viento',
    author: 'Vera Gil',
    year: '2023',
    description: 'Un libro desplegable reúne dibujos y transparencias en una secuencia de paisajes en movimiento.',
    detail: 'La disposición en acordeón permite leer la obra como una sucesión de páginas o como una imagen continua.',
    color: '#e4d9b9',
  },
  {
    id: 'pieza-015',
    nfcSerial: '04:D4:E5:F6:A7:B8:15',
    number: '15',
    category: 'Colección permanente',
    title: 'Lo que permanece',
    author: 'Nicolás Alba',
    year: '2025',
    description: 'Objetos recuperados forman un pequeño archivo de gestos cotidianos y memorias compartidas.',
    detail: 'Cada objeto conserva señales de su historia. Su relación con los demás propone nuevas formas de interpretar el conjunto.',
    color: '#d4dfa5',
  },
]
